services:
  - type: web
    name: ea-migrate-web
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: EXPO_NO_TELEMETRY
        value: "1"
      - key: NODE_ENV
        value: "production"
      - key: RENDER
        value: "true"

