name: Deploy to Render

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "ERROR: Missing secret RENDER_DEPLOY_HOOK_URL" 1>&2
            exit 1
          fi
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK_URL"
          echo "Triggered Render deploy"

